# Site Build Settings

# Jekyll-paginate-v2 configuration
#  pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title: 'LASSL'
description: 'Tech Blog'
author: 'PRDL LAB from MODULAB'

# Authors
authors:
  boseop.kim:
    name: boseop.kim
    display_name: boseop.kim
    email: boseop.kim@navercorp.com
    web: https://github.com/aisolab
    facebook: https://www.facebook.com/boseob.kim.16
    description: "언젠가는 자연어처리, 음성기술 기반으로 사람이 글과 말로 소통하는 것과 같은 수준의 인터페이스를 만들어보고 싶습니다."
  minho.ryu:
    name: minho.ryu
    display_name: minho.ryu
    email: ryumin93@sktbrain.com
    web: https://github.com/bzantium
    facebook: https://www.facebook.com/minho2ryu
    description: "세상을 한 층 더 편리하게 해줄 수 있는 서비스를 만들고 싶습니다."
  hyungjun.kim:
    name: hyungjun.kim
    display_name: hyungjun.kim
    email: soeque1@gmail.com
    web: https://github.com/soeque1
    facebook: https://www.facebook.com/hyungjun.kim.9887
    description: "Done is better than perfect."
  jaeho.kang:
    name: jaeho.kang
    display_name: jaeho.kang
    email: greennuri@gmail.com
    web: https://github.com/nuri428
    facebook: https://www.facebook.com/greennuri
    description: "에세이를 쓰는 AI를 만들어 보고 싶습니다 "
  hyoungseok.kim:
    name: hyoungseok.kim
    display_name: hyoungseok.kim
    email: hyoungseok.k@gmail.com
    web: https://github.com/alxiom
    facebook: https://www.facebook.com/alxiom
    description: "이 광활한 우주에 한 줌 먼지와도 같은 존재일 따름입니다."
 

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
